### PR TITLE
feature/argmaxdim - argmin/argmax along dimensions, adjust max/min of scalar

### PR DESCRIPTION
**Pull request by dsyme**
1. This addresses #232 for argmin/argmax along dimensions. These don't require differentiability as they only return tensors containing indexes, so are simpler than max/min along dimensions.

2. addresses part of #267 to adjust min/max in scalars

3. Fix a bug in max/min on integer tensors, where floating-point widening rules meant that float32 tensors were being produced.

4. Add testing for max/min and the new argmax/argmin along dimensions

### CODE REVIEW

**Comment by gbaydin** [comment]
I checked the api changes here and the test cases carefully and I also did an independent check with pytorch to ensure things are fine. 

Everything looks good, except the comment https://github.com/DiffSharp/DiffSharp/issues/267#issuecomment-738039698 about min/max failing for unsigned byte tensors. Should we address this here in this PR as well?

Otherwise I'm ready to merge.

**Comment by dsyme** [comment]
> Everything looks good, except the comment #267 (comment) about min/max failing for unsigned byte tensors. Should we address this here in this PR as well?

I consider this is a separate bug, I don't know the solution for it.  I'll open a separate issue on it.

**Comment by dsyme** [comment]
Separate bug at https://github.com/DiffSharp/DiffSharp/issues/284

**Comment by dsyme** [comment]
@gbaydin I'll leave you to merge

**Comment by gbaydin** [comment]
Thank you, sounds good.

**Pull request merged**
