### PR TITLE
web: Convert URLs to https to avoid mixed-content warnings

### PR DESCRIPTION
**Pull request by erydo**
Currently https://diffsharp.github.io shows mixed content warnings when viewed over HTTPS and refuses to load the MathJax to render the equations:

> Mixed Content: The page at 'https://diffsharp.github.io/DiffSharp/api-overview.html' was loaded over HTTPS, but requested an insecure script 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'. This request has been blocked; the content must be served over HTTPS.

This updates links and script URLs to HTTPS. It also removes the IE6-8 HTML5 shim, which no longer exists at the mentioned URL, and shouldn't be needed anymore anyway.

### CODE REVIEW

**Comment by dsyme** [comment]
Thank you!

**Comment by dsyme** [comment]
Are there things to fix in the original source docs in `master` too? 

Thanks

**Comment by erydo** [comment]
@dsyme Ah, of course, I wasn't certain where those were being generated from and just cleaned up with some `sed`. I'll go ahead and fix those originals and submit another PR. Thanks!

**Comment by dsyme** [comment]
Cool, thank you!

**Pull request merged**
