### PR TITLE
feature/avgpool - avgpool1d, avgpool2d, avgpool3d

### PR DESCRIPTION
**Pull request by dsyme**
Adds avgpool support

@gbaydin this uses the updated #89 to stop polluting Tensor,fs, and to have `DiffSharp.AvgPool.fs` extend all the necessary API surfacings all at once

### CODE REVIEW

**Comment by dsyme** [comment]
@gbaydin This is ready - testing for tensors and derivatives have been added

The reverse mode derivatives have been checked against python.  I've forgotten the python for checking the forward mode derivatives but I've pinned them down (and the forward mode implementations are trivial of course)

**Comment by dsyme** [comment]
close/reopen to trigger CI

**Comment by dsyme** [comment]
@gbaydin I've rebased this so it now uses the new extension API

It should be ready to go in

**Comment by gbaydin** [comment]
I checked everything carefully and this is good to go!

**Comment by dsyme** [comment]
Thanks!

**Pull request merged**
