### PR TITLE
Dropout

### PR DESCRIPTION
**Pull request by gbaydin**
This is to keep track of the work on dropout, batchnorm, and some related operations needed for machine learning.

### CODE REVIEW

**Comment by dsyme** [comment]
The changes so far are looking great

You might want to merge what you have, then I merge into #106, then we merge that PR, so we don't end up conflicting too much?   I'd love to get #106 in.

**Comment by gbaydin** [comment]
Ok let's do that. So I'm merging `feature/dropout` into `dev` now, keeping this PR open.

**Comment by dsyme** [comment]
Just to mention this already caused 128 conflicts with feature\torch2.  I'll fix them up....

**Comment by dsyme** [comment]
@gbaydin I've merged feature/torch2 - all looking good - it was good to replace the RandomIntegers by low/high RandomInt.

**Pull request merged**
