### PR TITLE
Main readme deadlink fix 

### PR DESCRIPTION
**Pull request by kevmal**
fix torch ipynb/fsx link

### CODE REVIEW

**Comment by dsyme** [comment]
@gbaydin coveralls debug build is failing:

```
Run dotnet csmacnz.Coveralls --opencover -i tests/DiffSharp.Tests/coverage.opencover.xml --useRelativePaths --repoToken  --commitId 1826c869dd9c4e3bfd04398f8c3cf8a3226c1a27 --commitBranch refs/pull/331/merge --commitAuthor "GitHub" --commitEmail noreply@github.com --commitMessage "Merge 6d358ef77a54dd32fa4e96df31ca2283568533f5 into a4d19929cb57f1f9c986b1f66c11f572aa55a32e" --jobId 584
Usage:
  csmacnz.Coveralls (--opencover | --dynamiccodecoverage | --monocov | --exportcodecoverage | --chutzpah | --lcov | --ncover | --reportgenerator | --multiple) -i ./opencovertests.xml (--repoToken <repoToken> | [--repoTokenVariable <repoTokenVariable>]) [-o ./opencovertests.json] [--dryrun] [--useRelativePaths [--basePath <path>] ] [--commitId <commitId> --commitBranch <commitBranch> [--commitAuthor <commitAuthor> --commitEmail <commitEmail> --commitMessage <commitMessage>] ] [--jobId <jobId>] [--serviceName <Name>] [--serviceNumber <Number>] [--pullRequest <pullRequestId>] [--treatUploadErrorsAsWarnings] [--parallel]
  csmacnz.Coveralls --completeParallelWork (--repoToken <repoToken> | [--repoTokenVariable <repoTokenVariable>]) [--serviceNumber <Number>]
  csmacnz.Coveralls --version
  csmacnz.Coveralls --help
```

**Comment by gbaydin** [comment]
`--repoToken` above seems to be missing here https://github.com/DiffSharp/DiffSharp/runs/2410101970

However it does work without issue in many other recent commits: https://github.com/DiffSharp/DiffSharp/actions

**Comment by gbaydin** [comment]
When the repo token is present it looks like this (it gets hidden in the ci page by `***`)

image

**Comment by gbaydin** [comment]
Ok it looks like this failed because the secrets are not available to builds of forks. Something like this: https://github.community/t/make-secrets-available-to-builds-of-forks/16166/2

**Comment by gbaydin** [comment]
It looks like the solution is to use `pull_request_target` instead of `pull_request` which executes the github action in the target branch of the PR to which the secrets are available. More details here: https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests

**Pull request merged**
