### PR TITLE
"Update fsdocs"

### PR DESCRIPTION
**Pull request by dsyme**
Replays the update to fsdocs

### CODE REVIEW

**Comment by dsyme** [comment]
@gbaydin There seems to be a problem running LibTorch code within the doc generation process on Linux with this updated doc generation tool. It's really hard to debug this unfortunately.

I think maybe it's better all our doc generation use only `DiffSharp-lite` and the reference backend.  I've adjusted the libtorch getting started to reflect this.

**Comment by dsyme** [comment]
Hmmm documentation evaluation is indeed having some kind of generic trouble

```
Evaluation failed and --strict is on
  file=Some(docs/documentation-extensions.fsx), asExpression=False, text=open DiffSharp

type Tensor with
    member a.sin() = 
        Tensor.Op
            { new UnaryOpElementwise("sin") with 
                member _.fRaw(a) = a.SinT()
                member _.dfda(a,f) = a.cos()
            }
            (a)
  stdout=
  stderr=
  inner exception: System.Exception: convMethodRef: could not bind to method '"Op"' of type 'DiffSharp.Tensor, DiffSharp.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.convMethodRef(cenv cenv, emEnv emEnv, Type parentTI, ILMethodRef mref) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 810
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.convMethodSpec(cenv cenv, emEnv emEnv, ILMethodSpec mspec) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 817
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitInstrCall@912.Invoke(Unit unitVar0) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 913
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitInstrTail(cenv cenv, ILGenerator ilG, ILTailcall tail, FSharpFunc`2 emitTheCall) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 900
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr callersRetAddrSlot, IntPtr callTarget, IntPtr retVal)
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitInstr(cenv cenv, ModuleBuilder modB, emEnv emEnv, ILGenerator ilG, ILInstr instr) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1090
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitCode(cenv cenv, ModuleBuilder modB, emEnv emEnv, ILGenerator ilG, ILCode code) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1361
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitILMethodBody(cenv cenv, ModuleBuilder modB, emEnv emEnv, ILGenerator ilG, ILMethodBody ilmbody) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1375
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitMethodBody[a,b](cenv cenv, ModuleBuilder modB, emEnv emEnv, FSharpFunc`2 ilG, b _name, MethodBody mbody) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1386
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildMethodPass3(cenv cenv, ILTypeRef tref, ModuleBuilder modB, TypeBuilder typB, emEnv emEnv, ILMethodDef mdef) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1577
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildTypeDefPass3@1845.Invoke(ILMethodDef mdef) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1845
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 497
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildTypeDefPass3(cenv cenv, FSharpList`1 nesting, ModuleBuilder modB, emEnv emEnv, ILTypeDef tdef) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 1845
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.buildModuleFragment(cenv cenv, emEnv emEnv, AssemblyBuilder asmB, ModuleBuilder modB, ILModuleDef m) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 2047
   at FSharp.Compiler.AbstractIL.ILRuntimeWriter.emitModuleFragment(ILGlobals ilg, Boolean emitTailcalls, emEnv emEnv, AssemblyBuilder asmB, ModuleBuilder modB, ILModuleDef modul, Boolean debugInfo, FSharpFunc`2 resolveAssemblyRef, FSharpFunc`2 tryFindSysILTypeRef) in D:\workspace\_work\1\s\src\fsharp\absil\ilreflect.fs:line 2128
   at FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.ProcessCodegenResults(CompilationThreadToken ctok, ErrorLogger errorLogger, FsiDynamicCompilerState istate, IncrementalOptimizationEnv optEnv, TcState tcState, TcConfig tcConfig, FSharpList`1 prefixPath, Boolean showTypes, Boolean isIncrementalFragment, String fragName, FSharpList`1 declaredImpls, IlxAssemblyGenerator ilxGenerator, IlxGenResults codegenResults) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 1158
   at FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.ProcessInputs(CompilationThreadToken ctok, ErrorLogger errorLogger, FsiDynamicCompilerState istate, FSharpList`1 inputs, Boolean showTypes, Boolean isIncrementalFragment, Boolean isInteractiveItExpr, FSharpList`1 prefixPath) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 1256
   at FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.EvalParsedDefinitions(CompilationThreadToken ctok, ErrorLogger errorLogger, FsiDynamicCompilerState istate, Boolean showTypes, Boolean isInteractiveItExpr, FSharpList`1 defs) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 1391
   at FSharp.Compiler.Interactive.Shell.clo@2201-369.Invoke(FsiDynamicCompilerState istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2213
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2115
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 371
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, Range m) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 418
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery(ErrorLogger x, Exception exn, Range m) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 431
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2115
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.execParsedInteractions(CompilationThreadToken ctok, TcConfig tcConfig, FsiDynamicCompilerState istate, FSharpOption`1 action, ErrorLogger errorLogger, FSharpOption`1 lastResult, CancellationToken cancellationToken) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2346
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.executeParsedInteractions(CompilationThreadToken ctok, TcConfig tcConfig, FsiDynamicCompilerState istate, FSharpOption`1 action, ErrorLogger errorLogger, FSharpOption`1 lastResult, CancellationToken cancellationToken) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2362
   at FSharp.Compiler.Interactive.Shell.clo@2387-370.Invoke(CompilationThreadToken ctok, TcConfig tcConfig, FsiDynamicCompilerState istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2388
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.mainThreadProcessAction[a,b](a ctok, FSharpFunc`2 action, b istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2384
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 371
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, Range m) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 418
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery(ErrorLogger x, Exception exn, Range m) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 431
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.mainThreadProcessAction[a,b](a ctok, FSharpFunc`2 action, b istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2384
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2115
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ReraiseIfWatsonable(Exception exn) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 371
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.ErrorRecovery(ErrorLogger x, Exception exn, Range m) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 418
   at FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.StopProcessingRecovery(ErrorLogger x, Exception exn, Range m) in D:\workspace\_work\1\s\src\fsharp\ErrorLogger.fs:line 431
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch[b](ErrorLogger errorLogger, FSharpFunc`2 f, b istate) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2115
   at FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.EvalInteraction(CompilationThreadToken ctok, String sourceText, String scriptFileName, ErrorLogger errorLogger, FSharpOption`1 cancellationToken) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 2528
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalInteractionNonThrowing(String code, FSharpOption`1 cancellationToken) in D:\workspace\_work\1\s\src\fsharp\fsi\fsi.fs:line 3067
   at <StartupCode$FSharp-Formatting-Common>.$YaafFSharpScripting.clo@845.Invoke(Unit unitVar0) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.Common/YaafFSharpScripting.fs:line 847
   at FSharp.Formatting.Internal.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.Common/YaafFSharpScripting.fs:line 789
   at FSharp.Formatting.Internal.FsiSession.save_[a](FSharpFunc`2 f, String text) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.Common/YaafFSharpScripting.fs:line 853
```

**Comment by dsyme** [comment]
@gbaydin There is some weird issue with evaluating scripts during documentation generation - the FSharp.Compiler.Service evaluation code underlying `fsdocs --eval` is not resolving overloaded methods correctly when used with DiffSharp

Basic script evaluation in fsdocs is working - there are many tests in the fsdocs repo. So this must have something to do with specifics when applied in the DiffSharp repo - e.g. mismatched FSharp.Core versions (though the tools are the same), or mismatched .NET Core versions (though fsdocs is running in .NET 5.0), or something else like this. 

Unfortunately it doesn't repro locally for me on Windows so it's hard for me to debug.  

We aren't actually currently relying on script evaluation during documentation generation in DiffSharp, so I recommend we actually just turn off `--eval` for now.  It is more important to update the documentation tool and author the documentation - we cn track this down later.

**Comment by dsyme** [comment]
@gbaydin I will merge this now, I've recorded the fsdocs bug about `--eval` not functioning correctly in this repo https://github.com/fsprojects/FSharp.Formatting/issues/662

**Comment by gbaydin** [comment]
@dsyme Sounds good to me. Thank you. Please let me know if I can do anything on Linux to reproduce and investigate the issue you mentioned.

https://github.com/fsprojects/FSharp.Formatting/issues/662 sounds like you found the source of the problem and it will be fixed in fsdocs code.

**Comment by dsyme** [comment]
> fsprojects/FSharp.Formatting#662 sounds like you found the source of the problem and it will be fixed in fsdocs code.

Needs a fix in ionide/proj-info so I will merge this

**Pull request merged**
