### PR TITLE
updating to latest TorchSharp

### PR DESCRIPTION
**Pull request by smoothdeveloper**
I increasingly like overload resolution error message :)

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
odd, it fails to build on CI despite it "builds on my machine".

https://github.com/DiffSharp/DiffSharp/blob/29af24ad69a96aace8a49420996861b2a3ca0fa9/src/DiffSharp.Backends.Torch/Torch.RawTensor.fs#L1456

it complains about this member not existing: 

https://github.com/dotnet/TorchSharp/blob/8157954c65932b7cf5ff92a40ff54d65b923e972/src/TorchSharp/Torch.cs#L418

Are there other changes than in Directory.Build.props to specify which TorchSharp library is used during CI builds?

**Comment by nhirschey** [comment]
I can build this on my windows machine as well, but the tests fail.

```cmd
Total tests: 516
     Passed: 503
     Failed: 12
    Skipped: 1
```

The failures appear to be related to float16 support. The tests pass if I change `Dtypes.FloatingPoint` to be the same as `Dtypes.FloatingPointExcept16s` in TestCombos.fs. The 12 failing tests could be fixed by making them use `Combos.FloatingPointExcept16s` instead of `Combos.FloatingPoint`. This might also fix the macOS CI failure ("terminating with uncaught exception of type c10::Error: "addmm_impl_cpu_" not implemented for 'Half'").

But the windows and linux CI build issue would remain.

**Comment by dsyme** [comment]
I did some updates, disabling the 16bit tests as you mention @nhirschey 

I then wanted to test CUDA and went back to `dev` head (uses TorchSharp 0.96.8) to check CUDA support is working there before checking it here. However I haven't been able yet to confirm CUDA is support is working because I'm getting an error on the most basic operations.  It could be a problem with my machine - it's a Windows 11 machine and maybe CUDA 11.3 isn't properly installed or the device isn't properly functional.  Will poke around a bit more

**Comment by nhirschey** [comment]
I'll try testing. I have been able to use recent TorchSharp on Cuda.

Is it possible that you need to update your CUDA SDK? The TorchSharp readme.md mentions a requirement for `(CPU/CUDA 11.3, Windows)`. I vaguely recall some issues when updating TorchSharp, and I can see that on my PC I installed `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7` 30 minutes after the `.nuget\packages` timestamps for torchSharp versions 0.99.6-0.100.2.

**Comment by dsyme** [comment]
> I have been able to use recent TorchSharp on Cuda.

That's encouraging. It might just be my machine TBH, though I was able to run some CUDA C++ samples just now.  

> Is it possible that you need to update your CUDA SDK? The TorchSharp readme.md mentions a requirement for (CPU/CUDA 11.3, Windows). I vaguely recall some issues when updating TorchSharp, and I can see that on my PC I installed C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7 30 minutes after the .nuget\packages timestamps for torchSharp versions 0.99.6-0.100.2.

11.3 seems to match the TorchSharp 0.96.8 that's in the `dev` head of DiffSharp.

I went back to the point I last contributed to the repo, commit 976d68b01bc722045d7953ab7b44807eafdd85da, when CUDA was also 11.3 and TorchSharp was 0.96.3, but I still get the same failures.  My poking around is recorded here: https://github.com/dsyme/DiffSharp/tree/poke

I may just try TorchSharp main on my machine and run the CUDA tests and see if anything works.  Though I've sort of timed out on this for today.

In any case let's get this green and work out CUDA later I think

**Comment by nhirschey** [comment]
For what it's worth, I *think* I can run `examples/classifier.fsx` on GPU using TorchSharp 0.100.3 with this PR.


```
dotnet build
dotnet test
```
Output:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped TestMNISTDataset [< 1 ms]

Passed!  - Failed:     0, Passed:   515, Skipped:     1, Total:   516, Duration: 3 m 57 s - DiffSharp.Tests.dll (net6.0)
```

Inside classifier.fsx, switch out to use 0.100.3 and GPU
```fsharp
#I "../tests/DiffSharp.Tests/bin/Debug/net6.0"
#r "DiffSharp.Core.dll"
#r "DiffSharp.Data.dll"
#r "DiffSharp.Backends.Torch.dll"

#r "nuget: TorchSharp-cuda-windows, 0.100.3"

open DiffSharp
open DiffSharp.Model
open DiffSharp.Compose
open DiffSharp.Optim
open DiffSharp.Data
open DiffSharp.Util

dsharp.config(backend=Backend.Torch, device=Device.GPU)
dsharp.seed(0)
```

The generated #r nuget package reference shows a TorchSharp 0.100.3 reference:
```fsharp
// Generated from #r "nuget:Package References"
// ============================================
//
// DOTNET_HOST_PATH:(C:\Program Files\dotnet\dotnet.exe)
// MSBuildSDKsPath:(C:\Program Files\dotnet\sdk\3.1.200-preview-014883\Sdks)
// MSBuildExtensionsPath:(C:\Program Files\dotnet\sdk\3.1.200-preview-014883\)
//
// References
//
#r @"C:/Users/nicho/.nuget/packages/google.protobuf/3.21.9/lib/net5.0/Google.Protobuf.dll"
#r @"C:/Users/nicho/.nuget/packages/sharpziplib/1.4.0/lib/net6.0/ICSharpCode.SharpZipLib.dll"
#r @"C:/Users/nicho/.nuget/packages/skiasharp/2.88.3/lib/net6.0/SkiaSharp.dll"
#r @"C:/Users/nicho/.nuget/packages/torchsharp/0.100.3/lib/net6.0/TorchSharp.dll"
```

Then inside `classifier.fsx` after defining the classifier model I can show the model is on the GPU device and I  can train the model for a few hundred minibatches (it eventually errors out due to a CUDA out of memory error).
```fsharp
> classifier.device
val classifier: Model<Tensor,Tensor> =
  Model(Conv2d(1, 32, [|3; 3|]), Conv2d(32, 64, [|3; 3|]), Linear(576, 128), Linear(128, 10))
val it: Device = Device (CUDA, 0)
```

**Comment by dsyme** [comment]
@nhirschey Great - what did you do to enable CUDA tests - did you use `dotnet test /p:DIFFSHARP_TESTGPU=true`?

thanks!

**Comment by dsyme** [comment]
@nhirschey This PR builds fine with latest F# preview, but it looks like the presence of some internal `cuda` thing in `torch.cuda` plus a type called `torch.cuda` caused problems in CI , which is using F# from .NET 6.0 

I think I fixed it with this: https://github.com/DiffSharp/DiffSharp/pull/443/commits/8cf2e1762ef39e1768da434cec1e40a31a7bc368

**Comment by dsyme** [comment]
@nhirschey @smoothdeveloper Cool this is green.

@nhirschey could you try the test run on CUDA please? Thank you

    dotnet test /p:DIFFSHARP_TESTGPU=true


BTW I noticed this thing on the GH public roadmap, though I don't hold my breath on the GPU capability becoming available any time too soon... https://github.com/github/roadmap/issues/505

One thing we could enable in CI is CPU-only testing using the CUDA-enabled binaries (which are large and complex things).  On my machine even this is failing back on CUDA 11.3 etc.

**Comment by nhirschey** [comment]
Using the most recent commit and `dotnet test /p:DIFFSHARP_TESTGPU=true` there's one failing test:

```fsharp
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped TestMNISTDataset [< 1 ms]
  Failed TestSeed [57 ms]
  Error Message:
     Expected: <tensor([7., 0., 3., 8., 5., 2., 4., 8., 9., 7., 4., 2., 4., 0., 9., 2., 5., 2., 7., 9., 2., 3., 6., 5., 4.])>
  But was:  <tensor([1., 1., 7., 6., 0., 8., 7., 3., 8., 3., 7., 6., 7., 9., 1., 9., 8., 1., 1., 3., 5., 9., 2., 2., 6.])>

  Stack Trace:
     at Tests.TestUtils.Assert.CheckEqual.Static[T](T expected, T actual) in C:\Users\nicho\Documents\GitHub\DiffSharp\tests\DiffSharp.Tests\TestUtils.fs:line 21
   at Tests.TestDiffSharp.TestSeed() in C:\Users\nicho\Documents\GitHub\DiffSharp\tests\DiffSharp.Tests\TestDiffSharp.fs:line 135


Failed!  - Failed:     1, Passed:   514, Skipped:     1, Total:   516, Duration: 7 m 6 s - DiffSharp.Tests.dll (net6.0)
```

**Comment by dsyme** [comment]
> Using the most recent commit and dotnet test /p:DIFFSHARP_TESTGPU=true there's one failing test:

Interesting!  Setting the seed for CUDA must use a different function - there's a comment about that here: https://github.com/DiffSharp/DiffSharp/blob/1bfe5b68cd240870815760eb4f6c489f5698923a/src/DiffSharp.Backends.Torch/Torch.RawTensor.fs#L1459-L1462

I'll disable the test for CUDA then merge this

**Comment by dsyme** [comment]
@nhirschey Good news: with CUDA 11.7 and this PR I can also run tests

**Comment by dsyme** [comment]
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped TestMNISTDataset [< 1 ms]

Passed!  - Failed:     0, Passed:   515, Skipped:     1, Total:   516, Duration: 1 m 1 s - DiffSharp.Tests.dll (net6.0)
```

**Pull request merged**
