### PR TITLE
Split out reference implementation of tensors

### PR DESCRIPTION
**Pull request by dsyme**
Not yet finished

### CODE REVIEW

**Comment by dsyme** [comment]
This is done

**Comment by gbaydin** [comment]
Thank you very much @dsyme !

**Comment by kevmal** [comment]
Maybe there should be a device id for multi gpu/cpu support? I could get a MXNet backend going pretty quick but perhaps it's too early?

**Comment by kevmal** [comment]
@dsyme @gbaydin I went ahead and prototyped an MXNet backend:
https://github.com/kevmal/DiffSharp/blob/mxnet/src/DiffSharp.Backend.MXNet/RawTensorFloat32CPU.fs

All tests pass. Though it's specifically `RawTensorFloat32CPU` the implementation easily generalizes to whatever.

**Pull request merged**
